// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: i18n/proto/i18n.proto

package truffle_i18n

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type I18NRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang string `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *I18NRequest) Reset() {
	*x = I18NRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_i18n_proto_i18n_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I18NRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NRequest) ProtoMessage() {}

func (x *I18NRequest) ProtoReflect() protoreflect.Message {
	mi := &file_i18n_proto_i18n_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NRequest.ProtoReflect.Descriptor instead.
func (*I18NRequest) Descriptor() ([]byte, []int) {
	return file_i18n_proto_i18n_proto_rawDescGZIP(), []int{0}
}

func (x *I18NRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *I18NRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type I18NResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *I18NResponse) Reset() {
	*x = I18NResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_i18n_proto_i18n_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I18NResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NResponse) ProtoMessage() {}

func (x *I18NResponse) ProtoReflect() protoreflect.Message {
	mi := &file_i18n_proto_i18n_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NResponse.ProtoReflect.Descriptor instead.
func (*I18NResponse) Descriptor() ([]byte, []int) {
	return file_i18n_proto_i18n_proto_rawDescGZIP(), []int{1}
}

func (x *I18NResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_i18n_proto_i18n_proto protoreflect.FileDescriptor

var file_i18n_proto_i18n_proto_rawDesc = []byte{
	0x0a, 0x15, 0x69, 0x31, 0x38, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x31, 0x38,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65,
	0x22, 0x33, 0x0a, 0x0b, 0x49, 0x31, 0x38, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x20, 0x0a, 0x0c, 0x49, 0x31, 0x38, 0x4e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x6f, 0x0a, 0x04, 0x49, 0x31, 0x38, 0x4e, 0x12,
	0x30, 0x0a, 0x01, 0x54, 0x12, 0x14, 0x2e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x49,
	0x31, 0x38, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x72, 0x75,
	0x66, 0x66, 0x6c, 0x65, 0x2e, 0x49, 0x31, 0x38, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x02, 0x54, 0x53, 0x12, 0x14, 0x2e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c,
	0x65, 0x2e, 0x49, 0x31, 0x38, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x49, 0x31, 0x38, 0x4e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x3b, 0x74,
	0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x5f, 0x69, 0x31, 0x38, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_i18n_proto_i18n_proto_rawDescOnce sync.Once
	file_i18n_proto_i18n_proto_rawDescData = file_i18n_proto_i18n_proto_rawDesc
)

func file_i18n_proto_i18n_proto_rawDescGZIP() []byte {
	file_i18n_proto_i18n_proto_rawDescOnce.Do(func() {
		file_i18n_proto_i18n_proto_rawDescData = protoimpl.X.CompressGZIP(file_i18n_proto_i18n_proto_rawDescData)
	})
	return file_i18n_proto_i18n_proto_rawDescData
}

var file_i18n_proto_i18n_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_i18n_proto_i18n_proto_goTypes = []interface{}{
	(*I18NRequest)(nil),  // 0: truffle.I18NRequest
	(*I18NResponse)(nil), // 1: truffle.I18NResponse
}
var file_i18n_proto_i18n_proto_depIdxs = []int32{
	0, // 0: truffle.I18N.T:input_type -> truffle.I18NRequest
	0, // 1: truffle.I18N.TS:input_type -> truffle.I18NRequest
	1, // 2: truffle.I18N.T:output_type -> truffle.I18NResponse
	1, // 3: truffle.I18N.TS:output_type -> truffle.I18NResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_i18n_proto_i18n_proto_init() }
func file_i18n_proto_i18n_proto_init() {
	if File_i18n_proto_i18n_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_i18n_proto_i18n_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I18NRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_i18n_proto_i18n_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I18NResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_i18n_proto_i18n_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_i18n_proto_i18n_proto_goTypes,
		DependencyIndexes: file_i18n_proto_i18n_proto_depIdxs,
		MessageInfos:      file_i18n_proto_i18n_proto_msgTypes,
	}.Build()
	File_i18n_proto_i18n_proto = out.File
	file_i18n_proto_i18n_proto_rawDesc = nil
	file_i18n_proto_i18n_proto_goTypes = nil
	file_i18n_proto_i18n_proto_depIdxs = nil
}
