// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: ws/proto/ws.proto

package truffle_ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *WriteMsgRequest) Reset() {
	*x = WriteMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_proto_ws_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMsgRequest) ProtoMessage() {}

func (x *WriteMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_ws_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMsgRequest.ProtoReflect.Descriptor instead.
func (*WriteMsgRequest) Descriptor() ([]byte, []int) {
	return file_ws_proto_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WriteMsgRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteMsgRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WriteMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id   int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WriteMsgResponse) Reset() {
	*x = WriteMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_proto_ws_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMsgResponse) ProtoMessage() {}

func (x *WriteMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_ws_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMsgResponse.ProtoReflect.Descriptor instead.
func (*WriteMsgResponse) Descriptor() ([]byte, []int) {
	return file_ws_proto_ws_proto_rawDescGZIP(), []int{1}
}

func (x *WriteMsgResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteMsgResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatchUpdateMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id   int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // newest id in the path
}

func (x *BatchUpdateMsgRequest) Reset() {
	*x = BatchUpdateMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_proto_ws_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUpdateMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMsgRequest) ProtoMessage() {}

func (x *BatchUpdateMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_ws_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMsgRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateMsgRequest) Descriptor() ([]byte, []int) {
	return file_ws_proto_ws_proto_rawDescGZIP(), []int{2}
}

func (x *BatchUpdateMsgRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BatchUpdateMsgRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatchUpdateMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *BatchUpdateMsgResponse) Reset() {
	*x = BatchUpdateMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_proto_ws_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUpdateMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMsgResponse) ProtoMessage() {}

func (x *BatchUpdateMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_ws_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMsgResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateMsgResponse) Descriptor() ([]byte, []int) {
	return file_ws_proto_ws_proto_rawDescGZIP(), []int{3}
}

func (x *BatchUpdateMsgResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_ws_proto_ws_proto protoreflect.FileDescriptor

var file_ws_proto_ws_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x0f,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x36, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a,
	0x15, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x32, 0x9c, 0x01, 0x0a, 0x02, 0x57, 0x73, 0x12, 0x43, 0x0a, 0x08, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x2e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c,
	0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x51, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x1e, 0x2e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c,
	0x65, 0x5f, 0x77, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_proto_ws_proto_rawDescOnce sync.Once
	file_ws_proto_ws_proto_rawDescData = file_ws_proto_ws_proto_rawDesc
)

func file_ws_proto_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_ws_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_proto_ws_proto_rawDescData)
	})
	return file_ws_proto_ws_proto_rawDescData
}

var file_ws_proto_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ws_proto_ws_proto_goTypes = []interface{}{
	(*WriteMsgRequest)(nil),        // 0: truffle.WriteMsgRequest
	(*WriteMsgResponse)(nil),       // 1: truffle.WriteMsgResponse
	(*BatchUpdateMsgRequest)(nil),  // 2: truffle.BatchUpdateMsgRequest
	(*BatchUpdateMsgResponse)(nil), // 3: truffle.BatchUpdateMsgResponse
}
var file_ws_proto_ws_proto_depIdxs = []int32{
	0, // 0: truffle.Ws.WriteMsg:input_type -> truffle.WriteMsgRequest
	2, // 1: truffle.Ws.BatchUpdateMsg:input_type -> truffle.BatchUpdateMsgRequest
	1, // 2: truffle.Ws.WriteMsg:output_type -> truffle.WriteMsgResponse
	3, // 3: truffle.Ws.BatchUpdateMsg:output_type -> truffle.BatchUpdateMsgResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_proto_ws_proto_init() }
func file_ws_proto_ws_proto_init() {
	if File_ws_proto_ws_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ws_proto_ws_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_proto_ws_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_proto_ws_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUpdateMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_proto_ws_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUpdateMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_proto_ws_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ws_proto_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_ws_proto_depIdxs,
		MessageInfos:      file_ws_proto_ws_proto_msgTypes,
	}.Build()
	File_ws_proto_ws_proto = out.File
	file_ws_proto_ws_proto_rawDesc = nil
	file_ws_proto_ws_proto_goTypes = nil
	file_ws_proto_ws_proto_depIdxs = nil
}
