// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: ws/proto/ws.proto

package truffle_ws

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WsClient is the client API for Ws service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WsClient interface {
	WriteMsg(ctx context.Context, opts ...grpc.CallOption) (Ws_WriteMsgClient, error)
	BatchUpdateMsg(ctx context.Context, in *BatchUpdateMsgRequest, opts ...grpc.CallOption) (*BatchUpdateMsgResponse, error)
}

type wsClient struct {
	cc grpc.ClientConnInterface
}

func NewWsClient(cc grpc.ClientConnInterface) WsClient {
	return &wsClient{cc}
}

func (c *wsClient) WriteMsg(ctx context.Context, opts ...grpc.CallOption) (Ws_WriteMsgClient, error) {
	stream, err := c.cc.NewStream(ctx, &Ws_ServiceDesc.Streams[0], "/truffle.Ws/WriteMsg", opts...)
	if err != nil {
		return nil, err
	}
	x := &wsWriteMsgClient{stream}
	return x, nil
}

type Ws_WriteMsgClient interface {
	Send(*WriteMsgRequest) error
	Recv() (*WriteMsgResponse, error)
	grpc.ClientStream
}

type wsWriteMsgClient struct {
	grpc.ClientStream
}

func (x *wsWriteMsgClient) Send(m *WriteMsgRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wsWriteMsgClient) Recv() (*WriteMsgResponse, error) {
	m := new(WriteMsgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wsClient) BatchUpdateMsg(ctx context.Context, in *BatchUpdateMsgRequest, opts ...grpc.CallOption) (*BatchUpdateMsgResponse, error) {
	out := new(BatchUpdateMsgResponse)
	err := c.cc.Invoke(ctx, "/truffle.Ws/BatchUpdateMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsServer is the server API for Ws service.
// All implementations must embed UnimplementedWsServer
// for forward compatibility
type WsServer interface {
	WriteMsg(Ws_WriteMsgServer) error
	BatchUpdateMsg(context.Context, *BatchUpdateMsgRequest) (*BatchUpdateMsgResponse, error)
	mustEmbedUnimplementedWsServer()
}

// UnimplementedWsServer must be embedded to have forward compatible implementations.
type UnimplementedWsServer struct {
}

func (UnimplementedWsServer) WriteMsg(Ws_WriteMsgServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteMsg not implemented")
}
func (UnimplementedWsServer) BatchUpdateMsg(context.Context, *BatchUpdateMsgRequest) (*BatchUpdateMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateMsg not implemented")
}
func (UnimplementedWsServer) mustEmbedUnimplementedWsServer() {}

// UnsafeWsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsServer will
// result in compilation errors.
type UnsafeWsServer interface {
	mustEmbedUnimplementedWsServer()
}

func RegisterWsServer(s grpc.ServiceRegistrar, srv WsServer) {
	s.RegisterService(&Ws_ServiceDesc, srv)
}

func _Ws_WriteMsg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WsServer).WriteMsg(&wsWriteMsgServer{stream})
}

type Ws_WriteMsgServer interface {
	Send(*WriteMsgResponse) error
	Recv() (*WriteMsgRequest, error)
	grpc.ServerStream
}

type wsWriteMsgServer struct {
	grpc.ServerStream
}

func (x *wsWriteMsgServer) Send(m *WriteMsgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wsWriteMsgServer) Recv() (*WriteMsgRequest, error) {
	m := new(WriteMsgRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Ws_BatchUpdateMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServer).BatchUpdateMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/truffle.Ws/BatchUpdateMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServer).BatchUpdateMsg(ctx, req.(*BatchUpdateMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ws_ServiceDesc is the grpc.ServiceDesc for Ws service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ws_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "truffle.Ws",
	HandlerType: (*WsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchUpdateMsg",
			Handler:    _Ws_BatchUpdateMsg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteMsg",
			Handler:       _Ws_WriteMsg_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ws/proto/ws.proto",
}
